### ISSUE TITLE
Feature Request : Daily kWh counter

### ISSUE THREAD

**Issue by TommySharpNZ** [KipK/openevse-gui-v2#23] opened 2023-01-28 22:55 UTC
Any thoughts on getting a daily counter added similar to the session and total counters?

**Comment by KipK** [comment] 2023-01-28 23:02
this is more a feature request for firmware .

If data is published through the API it can be easily added here.

**Comment by TommySharpNZ** [comment] 2023-01-29 05:23
Thanks @KipK I have logged a feature request (issue) on the main repository... Hopefully they pick it up...

**Comment by fhteagle** [comment] 2023-01-30 23:48
@TommySharpNZ  Not sure what use case is driving your request. However, I have been enjoying the utility of HomeAssistant logging and graphing all of my OpenEVSE use activity. Maybe that would get you the data / display you are looking for as well until this is implemented?

**Comment by TommySharpNZ** [comment] 2023-02-15 01:48
> @TommySharpNZ Not sure what use case is driving your request. However, I have been enjoying the utility of HomeAssistant logging and graphing all of my OpenEVSE use activity. Maybe that would get you the data / display you are looking for as well until this is implemented?

Would you mind sharing your config here on on the HomeAssistant forums?

I have tried to use the Total Usage sensor from OpenEVSE but I'm suspecting this only updates at the end of each charging session which means I get a chart with lots of jumps and not a proper usage line...
![image](https://user-images.githubusercontent.com/15130284/218906689-b7d599df-93c5-41a0-92c9-9f2933c20cd6.png)

**Comment by KipK** [comment] 2023-02-15 02:23
Yes total usage is only incremented at the end of a session. 
What I did to counter that is feeding a virtual counter on smart home side, that use the total +session elapsed while charging. And just the total when session ended.

**Comment by fhteagle** [comment] 2023-02-18 17:34
Disregard, after taking a closer look at the results of this method, I do not think it was working as intended.

**Comment by pdhoogh** [comment] 2023-02-23 16:22
Question: how/when does the OpenEVSE decide the charge session is a new session (reset to zero)? Now sometimes I want to start a new session with an energy limit and I need to add that to the current counter in order for it to work as I intend to, a bit weird...

I am not sure what the advantage would be to have a daily counter in OpenEVSE? I can see that in emoncms, but not in OpenEVSE functionality per se. Just my opinion.

**Comment by KipK** [comment] 2023-02-23 21:45
counter is reset at new vehicle connection.

**Comment by fhteagle** [comment] 2023-03-06 14:29
@TommySharpNZ  -

KipK's newest GUI revision has your feature, btw:

![Screenshot_20230306_072437](https://user-images.githubusercontent.com/9244278/223138467-d6b00647-ca6c-4715-bb16-b1da7bf93f7d.png)

Not sure when it will make it to the nightlies, or to a full release, but it is on its way!

**Comment by TommySharpNZ** [comment] 2023-03-06 20:56
Nice Nice Nice!
Although if it's just in @KipK new UI does not mean it will not be available in the "api" that the HomeAssistant integration uses?

**Comment by KipK** [comment] 2023-03-06 21:07
It's on the api yes

**Comment by TommySharpNZ** [comment] 2023-03-06 21:10
This is great news, thanks team!

**Comment by KipK** [comment] 2023-03-07 07:10
Fixed in EnergyMeter fw branch, waiting for merge

**Closed as completed by KipK** 2023-03-07 07:10 UTC
